### ISSUE TITLE
Relation ITU crash with "ITU-T J.222.1"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#32]
Trace: https://github.com/metanorma/mn-samples-itu/runs/321761831

```
fetching ITU-T J.222.1...
55
#<Thread:0x000055ea5e72d960@/usr/local/bundle/gems/relaton-bib-0.3.12/lib/relaton_bib/workers_pool.rb:17 run> terminated with exception (report_on_exception is true):
56
/usr/local/bundle/gems/relaton-itu-0.3.7/lib/relaton_itu/scrapper.rb:250:in `fetch_dates': undefined method `empty?' for nil:NilClass (NoMethodError)
57
	from /usr/local/bundle/gems/relaton-itu-0.3.7/lib/relaton_itu/scrapper.rb:66:in `parse_page'
58
	from /usr/local/bundle/gems/relaton-itu-0.3.7/lib/relaton_itu/hit.rb:22:in `fetch'
59
	from /usr/local/bundle/gems/relaton-itu-0.3.7/lib/relaton_itu/itu_bibliography.rb:71:in `block in fetch_pages'
60
	from /usr/local/bundle/gems/relaton-bib-0.3.12/lib/relaton_bib/workers_pool.rb:19:in `block (2 levels) in worker'
61
/usr/local/bundle/gems/relaton-itu-0.3.7/lib/relaton_itu/scrapper.rb:250:in `fetch_dates': undefined method `empty?' for nil:NilClass (NoMethodError)
62
	from /usr/local/bundle/gems/relaton-itu-0.3.7/lib/relaton_itu/scrapper.rb:66:in `parse_page'
63
	from /usr/local/bundle/gems/relaton-itu-0.3.7/lib/relaton_itu/hit.rb:22:in `fetch'
64
	from /usr/local/bundle/gems/relaton-itu-0.3.7/lib/relaton_itu/itu_bibliography.rb:71:in `block in fetch_pages'
65
	from /usr/local/bundle/gems/relaton-bib-0.3.12/lib/relaton_bib/workers_pool.rb:19:in `block (2 levels) in worker'
66
[relaton] processor "relaton_ogc" registered
67
```

**Comment by ronaldtse** [comment]
#<Thread:0x00007ffe0cd6c498@/Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/workers_pool.rb:17 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/workers_pool.rb:19:in `block (2 levels) in worker'
	3: from /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.7/lib/relaton_itu/itu_bibliography.rb:71:in `block in fetch_pages'
	2: from /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.7/lib/relaton_itu/hit.rb:22:in `fetch'
	1: from /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.7/lib/relaton_itu/scrapper.rb:66:in `parse_page'
/Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.7/lib/relaton_itu/scrapper.rb:250:in `fetch_dates': undefined method `empty?' for nil:NilClass (NoMethodError)

These also crash:

```adoc
* [[[ITU-T_G.718,ITU-T G.718]]], Recommendation ITU-T G.718 (2008), _Frame error robust narrow-band and wideband embedded variable bit-rate coding of speech and audio from 8 32 kbit/s_.

* [[[ITU-T_G.726,ITU-T G.726]]], Recommendation ITU-T G.726 (1990), _40, 32, 24, 16 kbit/s Adaptive Differential Pulse Code Modulation (ADPCM)_.

* [[[ITU-T_G.727,ITU-T G.727]]], Recommendation ITU-T G.727 (1990), _5-, 4-, 3- and 2-bit/sample embedded adaptive differential pulse code modulation (ADPCM)_.

* [[[ITU-T_G.728,ITU-T G.728]]], Recommendation ITU-T G.728 (2012), _Coding of speech at 16 kbit/s using low-delay code excited linear prediction_.

* [[[ITU-T_G.729.1,ITU-T G.729.1]]], Recommendation ITU-T G.729.1 (2006), _G.729-based embedded variable bit-rate coder: An 8-32 kbit/s scalable wideband coder bitstream interoperable with G.729_.
```

**Comment by ronaldtse** [comment]
Not yet working. You can try it out here: https://github.com/metanorma/mn-samples-itu/pull/55

```
fetching ITU-T G.718...
#<Thread:0x00007fa7b62d1530@/Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/workers_pool.rb:17 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	11: from /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/workers_pool.rb:19:in `block (2 levels) in worker'
	10: from /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.8/lib/relaton_itu/itu_bibliography.rb:71:in `block in fetch_pages'
	 9: from /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.8/lib/relaton_itu/hit.rb:22:in `fetch'
	 8: from /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.8/lib/relaton_itu/scrapper.rb:56:in `parse_page'
```

**Comment by ronaldtse** [comment]
Still erring with 0.3.9:

```
fetching ITU-T G.192...
bundler: failed to load command: metanorma (/Users/ronaldtse/.rbenv/versions/2.6.5/bin/metanorma)
NoMethodError: undefined method `to_xml' for nil:NilClass
Did you mean?  to_yaml
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.9/lib/relaton_itu/editorial_group.rb:31:in `block (2 levels) in to_xml'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/builder.rb:394:in `insert'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/builder.rb:377:in `method_missing'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.9/lib/relaton_itu/editorial_group.rb:31:in `block in to_xml'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/builder.rb:394:in `insert'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/builder.rb:377:in `method_missing'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-itu-0.3.9/lib/relaton_itu/editorial_group.rb:29:in `to_xml'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.3.12/lib/relaton_iso_bib/iso_bibliographic_item.rb:243:in `block (2 levels) in to_xml'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/builder.rb:394:in `insert'
```

**Comment by andrew2net** [comment]
The issue isn't stable, but I manage to catch it. Sometimes the site www.itu.int returns an empty body and status 502. Especially when we make many HTTP requests. So I didn't have the error when I make a single request. Fixed it.

**Comment by ronaldtse** [comment]
Thanks @andrew2net , confirmed!
